import type { MusicTrack } from './types'

// Shared catalog serializer used by ingest-local.ts and analyze-sections.ts so
// both write catalog.ts in the exact same format.
export function serializeCatalog(tracks: MusicTrack[]): string {
  const body = tracks.map(t => '  ' + JSON.stringify(t)).join(',\n')
  return `import type { MusicTrack } from './types'

// ── The curated music library ─────────────────────────────────────────────────
// AUTO-GENERATED by lib/music-library/ingest-local.ts (tracks) and enriched by
// analyze-sections.ts (startOffset / duration). Re-run the ingester to refresh
// the track list, then the analyzer to recompute the best-part offsets. Tracks
// are the creator's own, organized by mood category. Audio files live under
// music-library-files/ (not committed) and are read by the resolver.

export const MUSIC_CATALOG: MusicTrack[] = [
${body}${body ? ',' : ''}
]
`
}
