// ── Curated music library — mood-category model ───────────────────────────────
// The library is the creator's own organized folder of tracks, ingested from
// mood-named subfolders (see ingest-local.ts). Selection is driven by matching a
// video's mood to a music category, so the folders ARE the source of truth.
//
// Audio files are NOT committed (kept light) — the catalog stores a relative
// path into the music library directory (default ./music-library-files, override
// with MUSIC_LIBRARY_DIR) and the resolver reads the local file.

import type { ContentProfile } from '../video-analysis'

export type MusicCategory =
  | 'calm'
  | 'emotional'
  | 'sad'
  | 'happy'
  | 'funny'
  | 'energetic'
  | 'motivation'
  | 'inspiring'
  | 'curious'
  | 'mysterious'
  | 'dark'
  | 'gangster'

export const MUSIC_CATEGORIES: MusicCategory[] = [
  'calm', 'emotional', 'sad', 'happy', 'funny',
  'energetic', 'motivation', 'inspiring', 'curious',
  'mysterious', 'dark', 'gangster',
]

// Fallback category when nothing else fits — a safe, neutral bed.
export const NEUTRAL_CATEGORY: MusicCategory = 'calm'

export interface MusicTrack {
  id: string
  title: string
  // One or more mood categories (a track found in multiple mood folders carries
  // all of them, so it can match more than one kind of video).
  categories: MusicCategory[]
  // Path relative to the music library directory, e.g. "calm/after-dark.mp3".
  file: string
  durationSeconds: number | null
  // Seconds into the track where the best part (chorus/drop) begins — the mix
  // starts playback here so the strong section lands in the clip instead of the
  // intro. Filled by the analysis pass (analyze-sections.ts); 0/undefined = start
  // from the beginning.
  startOffset?: number
  // Sound-based description of the track, generated by listening to the actual
  // audio (Gemini) around the best part. Filled by describe-tracks.ts. Drives
  // smarter selection than picking at random inside a mood folder.
  profile?: MusicProfile
}

// What a track actually sounds like — derived from the audio itself, not the
// filename or the web. Used to match a track to a video's real mood.
export interface MusicProfile {
  description: string                       // one-line "what it sounds like"
  genre: string                             // e.g. "lo-fi pop", "orchestral"
  instrumentation: string[]                 // e.g. ["soft pads", "plucks"]
  tempoFeel: 'slow' | 'medium' | 'fast'     // subjective pace
  bpm?: number                              // Gemini's tempo estimate (approx)
  energy: number                            // 1 (ambient) – 10 (driving)
  moodWords: string[]                       // e.g. ["warm", "reflective"]
  goodFor: string[]                         // video vibes this fits
  avoidWhen: string[]                       // video vibes this clashes with
}

// What the selector scores a track against. hook/moodTag/scriptFormat come from
// the written script; profile/transcript (optional) come from Gemini's read of
// the actual footage so the match reflects what the clip really is, not just the
// mood tag someone typed. Selection falls back to script-only when they're absent.
export interface MusicSelectionContext {
  hook: string
  moodTag: string | null
  scriptFormat?: string
  profile?: ContentProfile | null
  transcript?: string | null
  // Which variant this pick is for. Same clip → same ranked shortlist, but each
  // variant takes a different rank so the versions vary musically instead of all
  // landing on the single best track.
  variantId?: string
}
